1 step
Toolll1/java-filmorate pull request #4
Opened 2023-02-12 12:06 UTC by Toolll1

1 step

2023-02-12 14:27 UTC, TomattmanYandex requested changes
Привет. слишком много усложенений в коде, пока что они не нужны, вы будете работать над этим проектом долго, и большая часть поменяется еще не раз, и куча логики которая сейчас была создана, будет просто удалена в дальнейшем. Рекомендую сейчас делать максимально просто, но чтобы удовлетворяло всем требованиям, а если чего то не будет хватать, то это исправится после ревью.
То же самое касается и названий переменных, классов и методов, не надо усложнять.
ЧТо касается тестов, то есть способ проверить что метод падает с ошибкой, рекомендую погуглить это и сделать по другому, ну и назвать методы чуть проще

2023-02-12 14:27 UTC, TomattmanYandex commented on pom.xml
> +        <dependency>
форматирование поехало

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.info("Количество фильмов в текущий момент: {}", films.size());
зачем это логировать? имеет смыл логировать, например то что сделали этот запрос или в других запросах, какой объект пришел

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        checkingTheCorrectnessOfTheData(newFilm);
почему бы не назвать метод просто validate

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new InvalidCreateException("Фильм с таким названием " + newFilm.getName() + " уже зарегистрирован.");
а ошибку просто ValidateException

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (newFilm.getId() == null) {
Когда мы создаем, нам без разницы пришел ли id нам все равно надо проставить новый, что будет если придёт id  уже существующего фильма, его просто перепишет

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.info("Новый фильм: {}", newFilm);
лучше добавлять чуть более информативные сообщения, а то непонятно что значит новый фильм, новый фильм запрошен, новый фильм удален, и т.д.
Например "добавлен новый фильм" одно слово но гораздо понятнее

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final Map<String, Film> films = new LinkedHashMap<>();
есть множество фильмов с одинаковыми названиями, как они буду храниться? лучше делать ключ id а потом делать доп проверки
тем более при добавлении ты не делаешь никаких проверок, да и не  было этого пока в задании, так зачем?

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (films.containsKey(newFilm.getName())) {
много логики, которая не очень имеет смысл, потому что при добавлении  например нету такой проверки, так же с обьектами мы чаще работаем по id, да id могут быть не только числа но и строки, и даже несколько строк, но тогда это надо обрабатывать совсем по другому, рекомендую пока убрать эту логику оставить только валидацию

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film put(@RequestBody Film newFilm) {
целиком метод очень непонятен, почему бы пока просто не сделать валидацию и если валиден то обнвление

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    protected int newId(Film newFilm) {
снова какая то странная логика

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (newFilm.getDescription().length() > 200) {
тут может быть NullPointerException, и ниже тоже

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +public class UserController {
комментарии все те же что и к классу выше

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/InvalidCreateException.java
> +public class InvalidCreateException extends RuntimeException{
я уже оставлял комментарии что лучше его назвать по другому

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final int duration;
вместо примитива лучше использовать класс обертку

2023-02-12 14:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
ты добавил библиотеку для валидации но не используешь ее

2023-02-12 14:27 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTests.java
> +        } catch (InvalidCreateException ignored) {
зачем делать try catch на runtime exception?
если это для проверки на ошибку, то есть способ проверить что вызов метода прокидывает ошибку

2023-02-12 17:22 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.info("Количество фильмов в текущий момент: {}", films.size());
хз, в теории так делали. Думал, что и тут попросят)

2023-02-13 10:02 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
@Data? почему не использую? геттеры, сеттеры используются.. На и в дальнейшем пригодится)

2023-02-13 10:58 UTC, Toolll1 commented
Блин.. Тесты были заточены под то, что в мапах ключами будут id! Изменил код, сделал максимально просто, а тестам всё понравилось!

2023-02-13 15:41 UTC, TomattmanYandex approved these changes
![og_og_1573255987235361093 1](https://user-images.githubusercontent.com/113444956/218503529-e60970af-f182-4b3d-98b9-3ef3f256991d.jpg)

2023-02-13 15:41 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        validate(newFilm);
идеально, коротко, ясно, понятно

2023-02-16 11:39 UTC, merged