2 step (1 iteration)
Toolll1/java-filmorate pull request #5
Opened 2023-02-27 18:01 UTC by Toolll1

2023-02-28 12:06 UTC, TomattmanYandex requested changes
Привет, еще есть что поправить

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @Autowired
вариант как это сделать получше - аннотация на класс @RequiredArgsConstructor и тогда самому конструктор писать не надо, а если появятся еще зависимости от сервисов, то их достаточно будет только объявить, а все остальное сгенерируется автоматически

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandler.java
> +                Map.of("Ошибка валидации: ", e.getMessage()),
1) map Это хранилище типа ключ значение - лучше чтобы ключ бы одинаковый, например тут подойдет ключ message, а то что сейчас записывается в ключ больше похоже на еще одно сообщение
2) обычно все же все логируемые сообщения, ключи, все кроме самих данных хранят на английском, так как очень часто команды распределенные, могут быть из разных стран, то английский лучше подходит
(второй пункт это больше как рекомендация, исправлять не обязательно, но лучше привыкать)

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorResponse.java
> +public class ErrorResponse {
где этот класс используется, кажется что в Error хендлере должен возвращаться респонз с этим обьектом

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<User> like;
это не один лайк а много, лучше переменную обозвать likes

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Set<Integer> friends;
модификатор доуступа

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
тут то же самое что и в котроллере по поводу @RequiredArgsConstructor
а логгер можно получить аннотацией Lombook @Slf4j

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Map<Integer, Film> findAll() {
обычно на уровне сервиса определяют всю бизнес логику и преобразования, лучше чтобы метод возвращал сразу список

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return filmStorage.findAll().get(filmId);
а для такого лучше на уровне хранилища сделать метод получения по id

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validate(newFilm);
Валидацию обычно делают на уровне контроллера

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public String addLikes(int id, int userId) {
почему бы не назвать переменную filmId будеть гораздо понятнее

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public String addLikes(int id, int userId) {
почему бы не получить сразу фильм по Id и если он null кидать ошибку, если не null то обрабатывать дальше, меньше запросов в хранилище, выполнение быстрее

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            likes = filmStorage.findAll().get(id).getLike();
а смысл этого действия?
можно переделать так
если сет равен null то сетаем new HashSet
а блок else не нужен

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        likes.add(userStorage.findAll().get(userId));
ты уже проверил что юзер есть, а его id пришгел в параметре, зачем снова получать пользователя

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.findAll().get(id).setLike(likes);
зачем серать значение строчки 84-91 можно преобразовать в 
if(film.getLikes() == null) {
   film.setLikes(new HashSet()); // если не инициализирован сет лайков, инициализировали
}
film.getLikes().add(userId); //сразу в него добавили лайк

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.findAll() == null) {
лучше сделать так чтобы filmStorage.findAll() никогда не возвращал null и тогда эта проверка не нужна

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userStorage.findAll() == null) {
то же самое

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.findAll().get(id).getLike().contains(userStorage.findAll().get(userId))) {
а тут можно простоу фильма из списка лайков удалить id пользователя, если он был, то удалится, если не было, то значит в списке его в любом случае не будет

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (count <= 0) {
и снова, лучше эту переменную валидировать на контроллере, а тут уже если число меньше нуля, то возвращать пустой список, а логику на это можно реализовать не выделяя отдельных блоков кода по это

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else if (filmStorage.findAll().isEmpty()) {
а вообще реализация этого метода лушче чтобы была другая, получили все фильмы, отсортировали список компаратором самописным (по количеству лайков) забрали первые limit элементов

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
тут скорее всего будет все то же что и в FilmService

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Map<Integer, Film> findAll();
по заданию тут должна быть логика - 
фрагмент из задания
имплементирующие новые интерфейсы, и перенесите туда всю логику хранения, обновления и поиска объектов.
следовательно поиск по ретйингу тоже стоит перенести в хранилище

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Map<Integer, Film> findAll() {
лучше возвращать список, а еще закинуть сюда логику работы с данными, и обновление

2023-02-28 12:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Map<Integer, User> findAll() {
то же что и в предыдущем классе

2023-03-01 10:40 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @Autowired
сделал

2023-03-01 10:42 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorResponse.java
> +public class ErrorResponse {
не удалил его перед отправкой) пробовал несколько вариантов обработки ошибок. решил остановиться на уже существующем ResponseEntity 
ErrorResponse удалил

2023-03-01 10:56 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandler.java
> +                Map.of("Ошибка валидации: ", e.getMessage()),
translated everything

2023-03-01 10:57 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<User> like;
+

2023-03-01 10:57 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Set<Integer> friends;
+

2023-03-01 11:01 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
+

2023-03-01 11:03 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Map<Integer, Film> findAll() {
+

2023-03-01 11:09 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return filmStorage.findAll().get(filmId);
+

2023-03-01 11:10 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public String addLikes(int id, int userId) {
+

2023-03-01 11:15 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        validate(newFilm);
+

2023-03-01 11:26 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public String addLikes(int id, int userId) {
+

2023-03-01 11:35 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            likes = filmStorage.findAll().get(id).getLike();
+

2023-03-01 11:35 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        likes.add(userStorage.findAll().get(userId));
+

2023-03-01 11:41 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        filmStorage.findAll().get(id).setLike(likes);
+

2023-03-01 14:01 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @Autowired
+

2023-03-01 14:02 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandler.java
> +                Map.of("Ошибка валидации: ", e.getMessage()),
+

2023-03-01 14:02 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorResponse.java
> +public class ErrorResponse {
+

2023-03-01 14:02 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<User> like;
+

2023-03-01 14:02 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Set<Integer> friends;
+

2023-03-01 14:03 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.findAll() == null) {
+

2023-03-01 14:03 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (userStorage.findAll() == null) {
+

2023-03-01 14:03 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.findAll().get(id).getLike().contains(userStorage.findAll().get(userId))) {
+

2023-03-01 14:03 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (count <= 0) {
+

2023-03-01 14:03 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else if (filmStorage.findAll().isEmpty()) {
+

2023-03-01 14:04 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
+

2023-03-01 14:04 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Map<Integer, Film> findAll();
+

2023-03-01 14:04 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public Map<Integer, Film> findAll() {
+

2023-03-01 14:04 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Map<Integer, User> findAll() {
+

2023-03-02 11:56 UTC, TomattmanYandex approved these changes
Привет, принято, те комменты что новые, не критичны, но лучше к следующему спринту поправить

2023-03-02 11:56 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandler.java
> +                Map.of("message: ", e.getMessage()),
Вариант еще лучше, сделать класс для этого, она автоматически сериализуется с именами его полей,
А так может получиться что в одном сообщение будет message, во втором mesage и т.д.
Второй вариант, если текст используется больше чем в одном месте, то его лучше вынести в константу

2023-03-02 11:56 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorHandler.java
> +                Map.of("message: ", e.getMessage()),
у тебя же был класс ErrorResponse лучше было бы создать обьект этого класса и возвращать уже его

2023-03-02 11:56 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Map<Integer, Film> findAll();
а вообще лучше бы чтобы взвращался список

2023-03-15 12:25 UTC, merged