Add database
Toolll1/java-filmorate pull request #7
Opened 2023-03-30 17:56 UTC by Toolll1

2023-03-31 11:06 UTC, TomattmanYandex requested changes
Привет, хорошая работа.
от тестов вообще в восторге, но переделать намного стоит

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    private int id;
Лучше класс обертка

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    private int id;
аналогично

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        searchId(filmId);
для удаления не обязательно проверять существование в базе фильма и пользователя, тут нам важна только запись, с этими данными, если такой найдено не будет, то ничего удалено не будет

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.findAll().values().stream()
это можно сделать одним запросом в базу, будет меньше передано данных, меньше нагрузка, и вообще

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void searchId(int... ids) {
очень непонятное название метода

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void searchId(int... ids) {
лучше назвать как ни будь вроде isExist

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Integer friendId : userOneFriends) {
стоит попробовать это сделать одним запросом в базу, да будет сложнее, но лучше

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +    public void deleteLikes(int filmId, int userId) {
можно было бы сделать отдельный Storage для лайков и использовать его (но это не обязательно)

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                film.getId(),
генерацию id стоит перенести из сервиса в саму базу 
гуглить по словам sequince generator sql

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        return findAll().get(film.getId());
зачем использовать findAll если можно findById

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        return findAll().get(id);
Плохая реализация, надо получить 1 фильм, но для этого получать сразу все в базе, и собирать в объекты.
А что если будет в таблицы , сотни, тысячи фильмов?

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        String sqlQuery = "SELECT f.film_id, f.name, string_agg(distinct g.genre_id::char,',') as genre_id, f.description," +
снова не самый лучший подход
собирать id в строку разделенную запятыми, лучше получить несколько записей для одного фильма, а потмо сами фильмы сгрупировать, или сделать два отдельных запроса, один для всех фильмов, второй для всех жанров для всех этих фильмов (но важно избежать того, чтобы было при получнеии n фильмов n дополнительных запросов, только 1)

2023-03-31 11:06 UTC, TomattmanYandex commented on src/main/resources/schema.sql
> +user_id   int not null references users(user_id),
где то есть форматирование, где то нету, где то table Где то TABLE стоит привести к одному виду

2023-04-01 15:40 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    private int id;
+

2023-04-01 15:40 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    private int id;
+

2023-04-01 15:40 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        searchId(filmId);
+

2023-04-01 17:21 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.findAll().values().stream()
+

2023-04-01 17:22 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void searchId(int... ids) {
+

2023-04-01 17:46 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                film.getId(),
+

2023-04-01 18:05 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        return findAll().get(film.getId());
+

2023-04-01 18:51 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        return findAll().get(id);
+

2023-04-01 18:51 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        String sqlQuery = "SELECT f.film_id, f.name, string_agg(distinct g.genre_id::char,',') as genre_id, f.description," +
+

2023-04-01 18:51 UTC, Toolll1 commented on src/main/resources/schema.sql
> +user_id   int not null references users(user_id),
+

2023-04-01 19:11 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        for (Integer friendId : userOneFriends) {
+

2023-04-01 21:27 UTC, TomattmanYandex requested changes
Остался один момент который надо исправить

2023-04-01 21:27 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        String sql = "select g.genre_id, g.name\n" +
все еще для каждого фильма будет отдельный запрос за жанрами
это надо исправить
вариант как это решить

1 получить все фильмы, без жанров 
2 сделать из них обьекты
3 собрать лист только Id фильмов
4 сделать запрос вот он прям таким и должен быть, только подкоректировать чтобы валтдный был
Select filmid, genreId, genreName from filmGenres join genres where filmId in (список id фильмов)
5 пройтись по резалт сету и всем фильмам из списка (или мапы) добавить записи из резалт сета

пункты 1 и 2 уже есть, осталось сделать только оставшиеся, чтобы за жанрами был один запрос для любого количества фильмов

2023-04-02 09:36 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +        String sql = "select g.genre_id, g.name\n" +
это было жестоко...
всю голову себе сломал, как вернуть не Genre, а film_id + Genre.. или film_id + List<Genre>
надеюсь, тебе понравится)))

2023-04-03 13:44 UTC, TomattmanYandex approved these changes

2023-04-03 13:44 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                .map(film -> String.valueOf(film.getId())).collect(Collectors.joining(",")) + ")");
отлично, так и надо было, единственно я бы все же посоветовал, через плейсхолдеры заполнять запрос
и подготовить список id заранее

2023-04-03 17:36 UTC, Toolll1 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDbStorage.java
> +                .map(film -> String.valueOf(film.getId())).collect(Collectors.joining(",")) + ")");
Что в этом контексте значит "плейсхолдер"? Гугл говорит, это подсказки при заполнении форм

2023-04-06 13:49 UTC, merged